-- ── VERVALLEN ────────────────────────────────────────────────────────────────
-- Deze migratie refereerde aan public.actions, wat niet bestaat.
-- Sitecontent wordt opgeslagen in public.instellingen (sleutel: sitecontent).
-- Zie migrations/004_sitecontent_seed.sql voor de correcte migratie.
